// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate(arg1) {
  return window['go']['main']['App']['ApplyUpdate'](arg1);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function Connect(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3, arg4, arg5);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function HostGenToken() {
  return window['go']['main']['App']['HostGenToken']();
}

export function HostStart(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['HostStart'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function HostStatus() {
  return window['go']['main']['App']['HostStatus']();
}

export function HostStop() {
  return window['go']['main']['App']['HostStop']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ServiceUp() {
  return window['go']['main']['App']['ServiceUp']();
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
