// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {update} from '../models';
import {engine} from '../models';
import {config} from '../models';
import {main} from '../models';
import {acl} from '../models';

export function ApplyUpdate(arg1:string):Promise<void>;

export function CheckUpdate():Promise<update.Release>;

export function Connect(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<engine.Status>;

export function Disconnect():Promise<engine.Status>;

export function HostGenToken():Promise<string>;

export function HostStart(arg1:config.Config):Promise<void>;

export function HostStatus():Promise<main.HostState>;

export function HostStop():Promise<void>;

export function ParseACL(arg1:string):Promise<Array<acl.Rule>>;

export function QuitApp():Promise<void>;

export function ServerServiceUp():Promise<boolean>;

export function ServiceUp():Promise<boolean>;

export function Status():Promise<engine.Status>;

export function Version():Promise<string>;
