// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeviceID() {
  return window['go']['main']['App']['DeviceID']();
}

export function Join(arg1, arg2, arg3) {
  return window['go']['main']['App']['Join'](arg1, arg2, arg3);
}

export function Refresh() {
  return window['go']['main']['App']['Refresh']();
}
