// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';

export function Connect(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<engine.Status>;

export function Disconnect():Promise<engine.Status>;

export function ServiceUp():Promise<boolean>;

export function Status():Promise<engine.Status>;
